$axure.loadCurrentPage({
  "url":"game.html",
  "generationDate":new Date(1476259093927.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b67da6a4d89649a3b5531ea384777f19",
    "type":"Axure:Page",
    "name":"GAME",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"70c21b409fb54026bafaef909c2d7c32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":1280,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed98aa4e6e9e4daa97ffe4f048a964b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":1280,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u7.png"}},
{
          "id":"ffb63a88c8f44613aea481a716cc9dbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":413,
              "y":26},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39fc85de950c494eaf8330f13a5a0103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":413,
                  "y":26},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 INDEX",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"cb92dbe59a704edebf136bec117b5068",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":672,
              "y":26},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d76288d57f24f7f927db7605acc6b27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":672,
                  "y":26},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 DESIGN",
                      "target":{
                        "targetType":"page",
                        "url":"design.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"8247baacb12e450dabc4b2f9b33bc2cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":899,
              "y":26},
            "size":{
              "width":99,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e20969c272e849d49894b7c5015c63b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":899,
                  "y":26},
                "size":{
                  "width":99,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FRONT-END",
                      "target":{
                        "targetType":"page",
                        "url":"front-end.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"6998d70280d04ce1a8bd143df1a58eb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1173,
              "y":26},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d309314dd224431a5aba77e507b4d19",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1173,
                  "y":26},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GAME",
                      "target":{
                        "targetType":"page",
                        "url":"game.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7ec988755c4c4377983ef88086904886",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1390,
              "y":26},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b0debaf78c54cae834432bf4e95ffa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1390,
                  "y":26},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GITHUB",
                      "target":{
                        "targetType":"page",
                        "url":"github.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"591c6aa477dd48f8ad12b0f4c0e7f976",
          "label":"游戏灰",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":69},
            "size":{
              "width":1280,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b67ede385664484aab3eba2a61a739ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":69},
                "size":{
                  "width":1280,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/game/游戏灰_u12.png"}},
{
          "id":"6e9eefca8ce044d28d982add6422402b",
          "label":"游戏灰",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":269},
            "size":{
              "width":1280,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e40d05c4f8a942cabcd35737b85f1c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":269},
                "size":{
                  "width":1280,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/game/游戏灰_u14.png"}},
{
          "id":"74f6be78ecec482f9b5e193df5ee46c1",
          "label":"游戏灰",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":469},
            "size":{
              "width":1280,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67d92e109c814f08900fd4b9a3b2bdaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":469},
                "size":{
                  "width":1280,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/game/游戏灰_u16.png"}},
{
          "id":"1ad2dbafd66645e0b15297bbd0977bb5",
          "label":"游戏0灰",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":69},
            "size":{
              "width":1280,
              "height":200},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e22cb9066b3418e95a799d68058f054",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":69},
                "size":{
                  "width":1280,
                  "height":200},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/game/游戏0灰_u18.jpg"}},
{
          "id":"f81d61efca0d4e9aae0f6b7972b2e320",
          "label":"游戏1灰",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":269},
            "size":{
              "width":1280,
              "height":200},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc9edfe8fba2462a8096e001bc30aa4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":269},
                "size":{
                  "width":1280,
                  "height":200},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/game/游戏1灰_u20.jpg"}},
{
          "id":"633bbf0e8485432696c73092b6d9490b",
          "label":"游戏2灰",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":469},
            "size":{
              "width":1280,
              "height":200},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36dd9fa416c64c8486d80a0e8427fefb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":469},
                "size":{
                  "width":1280,
                  "height":200},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/game/游戏2灰_u22.jpg"}},
{
          "id":"90685a9e4dee41ea91cd8ae06e6067b5",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":269},
            "size":{
              "width":1280,
              "height":200}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://hs.blizzard.cn/landing",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://hs.blizzard.cn/landing",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 游戏1灰 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["f81d61efca0d4e9aae0f6b7972b2e320"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 游戏1灰 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["f81d61efca0d4e9aae0f6b7972b2e320"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"6a11329e4ae24422848bd21c67197c49",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":308.5,
              "y":469},
            "size":{
              "width":1280,
              "height":200}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://ow.blizzard.cn/home",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://ow.blizzard.cn/home",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 游戏2灰 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["633bbf0e8485432696c73092b6d9490b"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 游戏2灰 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["633bbf0e8485432696c73092b6d9490b"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"a5df80b28a7141afbe9c8237fb91f00f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":310,
              "y":69},
            "size":{
              "width":1280,
              "height":200}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 http://lol.qq.com/",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"http://lol.qq.com/",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"current"}]}]},
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 游戏0灰 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["1ad2dbafd66645e0b15297bbd0977bb5"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 游戏0灰 淡入淡出 500 ms",
                      "objectsToFades":[{
                          "objectPath":["1ad2dbafd66645e0b15297bbd0977bb5"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"fade",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "70c21b409fb54026bafaef909c2d7c32":{
      "scriptId":"u0"},
    "ed98aa4e6e9e4daa97ffe4f048a964b9":{
      "scriptId":"u1"},
    "ffb63a88c8f44613aea481a716cc9dbe":{
      "scriptId":"u2"},
    "39fc85de950c494eaf8330f13a5a0103":{
      "scriptId":"u3"},
    "cb92dbe59a704edebf136bec117b5068":{
      "scriptId":"u4"},
    "6d76288d57f24f7f927db7605acc6b27":{
      "scriptId":"u5"},
    "8247baacb12e450dabc4b2f9b33bc2cc":{
      "scriptId":"u6"},
    "e20969c272e849d49894b7c5015c63b4":{
      "scriptId":"u7"},
    "6998d70280d04ce1a8bd143df1a58eb4":{
      "scriptId":"u8"},
    "0d309314dd224431a5aba77e507b4d19":{
      "scriptId":"u9"},
    "7ec988755c4c4377983ef88086904886":{
      "scriptId":"u10"},
    "6b0debaf78c54cae834432bf4e95ffa6":{
      "scriptId":"u11"},
    "591c6aa477dd48f8ad12b0f4c0e7f976":{
      "scriptId":"u12"},
    "b67ede385664484aab3eba2a61a739ff":{
      "scriptId":"u13"},
    "6e9eefca8ce044d28d982add6422402b":{
      "scriptId":"u14"},
    "e40d05c4f8a942cabcd35737b85f1c5b":{
      "scriptId":"u15"},
    "74f6be78ecec482f9b5e193df5ee46c1":{
      "scriptId":"u16"},
    "67d92e109c814f08900fd4b9a3b2bdaa":{
      "scriptId":"u17"},
    "1ad2dbafd66645e0b15297bbd0977bb5":{
      "scriptId":"u18"},
    "2e22cb9066b3418e95a799d68058f054":{
      "scriptId":"u19"},
    "f81d61efca0d4e9aae0f6b7972b2e320":{
      "scriptId":"u20"},
    "fc9edfe8fba2462a8096e001bc30aa4e":{
      "scriptId":"u21"},
    "633bbf0e8485432696c73092b6d9490b":{
      "scriptId":"u22"},
    "36dd9fa416c64c8486d80a0e8427fefb":{
      "scriptId":"u23"},
    "90685a9e4dee41ea91cd8ae06e6067b5":{
      "scriptId":"u24"},
    "6a11329e4ae24422848bd21c67197c49":{
      "scriptId":"u25"},
    "a5df80b28a7141afbe9c8237fb91f00f":{
      "scriptId":"u26"}}});