$axure.loadCurrentPage({
  "url":"材料与工艺.html",
  "generationDate":new Date(1476259092017.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"488f2ef0f282464096f36281e623e391",
    "type":"Axure:Page",
    "name":"材料与工艺",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ccef7129c36140ff985e7ec73e70a4c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":1280,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"135ab74a5a85471287e12ec9fe92b892",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":1280,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u7.png"}},
{
          "id":"e6acb178f7ee4a4887bc0dd9dfce6c09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":413,
              "y":26},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f1ddbd82fda41d7b855a387bab34d41",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":413,
                  "y":26},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 INDEX",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"1d7b3e7005654d7c8d20b88472a22e8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":672,
              "y":26},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d62de7a730d4f20affea155350ecd2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":672,
                  "y":26},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 DESIGN",
                      "target":{
                        "targetType":"page",
                        "url":"design.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b8bf36735e524f7ea821f6abc1183ffe",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":899,
              "y":26},
            "size":{
              "width":99,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e152895a6254c08aa2638eee9edd562",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":899,
                  "y":26},
                "size":{
                  "width":99,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FRONT-END",
                      "target":{
                        "targetType":"page",
                        "url":"front-end.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"24bacb0785174c2ab55ebbd97d9f8034",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1173,
              "y":26},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e5ba8eb34c4aa98faba766640361a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1173,
                  "y":26},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GAME",
                      "target":{
                        "targetType":"page",
                        "url":"game.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a65b3a3d6b024b4081f17d6fb5a0cd4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1390,
              "y":26},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5710688c1dff4984bd561da00c94dc3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1390,
                  "y":26},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GITHUB",
                      "target":{
                        "targetType":"page",
                        "url":"github.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"cbeeb57a250347de888144c170e6f3b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":310,
              "y":67},
            "size":{
              "width":1280,
              "height":1360},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecf92a18da414b1e933adf5e5663cdb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":310,
                  "y":67},
                "size":{
                  "width":1280,
                  "height":1360},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/材料与工艺/u12.png"}},
{
          "id":"6f9c6c9cba684618b93533151ada3792",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":870,
              "y":90},
            "size":{
              "width":161,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8081731ea1454165a3c5ed7ebf6928b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":870,
                  "y":90},
                "size":{
                  "width":161,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d71acb49a0ab45a6a1e3f3b8b722c81b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":430,
              "y":190},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8f8451f089e4d609fd5460ad526afa4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":430,
                  "y":190},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/材料与工艺/u16.jpg"}},
{
          "id":"52b83cb1a4cc4b5c949b0685493f7110",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1023,
              "y":190},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d0ac8ae0534b2da6694161ee32f3d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1023,
                  "y":190},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/材料与工艺/u18.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "ccef7129c36140ff985e7ec73e70a4c2":{
      "scriptId":"u0"},
    "135ab74a5a85471287e12ec9fe92b892":{
      "scriptId":"u1"},
    "e6acb178f7ee4a4887bc0dd9dfce6c09":{
      "scriptId":"u2"},
    "3f1ddbd82fda41d7b855a387bab34d41":{
      "scriptId":"u3"},
    "1d7b3e7005654d7c8d20b88472a22e8f":{
      "scriptId":"u4"},
    "1d62de7a730d4f20affea155350ecd2d":{
      "scriptId":"u5"},
    "b8bf36735e524f7ea821f6abc1183ffe":{
      "scriptId":"u6"},
    "8e152895a6254c08aa2638eee9edd562":{
      "scriptId":"u7"},
    "24bacb0785174c2ab55ebbd97d9f8034":{
      "scriptId":"u8"},
    "58e5ba8eb34c4aa98faba766640361a7":{
      "scriptId":"u9"},
    "a65b3a3d6b024b4081f17d6fb5a0cd4d":{
      "scriptId":"u10"},
    "5710688c1dff4984bd561da00c94dc3a":{
      "scriptId":"u11"},
    "cbeeb57a250347de888144c170e6f3b5":{
      "scriptId":"u12"},
    "ecf92a18da414b1e933adf5e5663cdb7":{
      "scriptId":"u13"},
    "6f9c6c9cba684618b93533151ada3792":{
      "scriptId":"u14"},
    "8081731ea1454165a3c5ed7ebf6928b4":{
      "scriptId":"u15"},
    "d71acb49a0ab45a6a1e3f3b8b722c81b":{
      "scriptId":"u16"},
    "f8f8451f089e4d609fd5460ad526afa4":{
      "scriptId":"u17"},
    "52b83cb1a4cc4b5c949b0685493f7110":{
      "scriptId":"u18"},
    "06d0ac8ae0534b2da6694161ee32f3d2":{
      "scriptId":"u19"}}});