$axure.loadCurrentPage({
  "url":"人机工程学.html",
  "generationDate":new Date(1476259092647.52),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"55ee43fa0a0546c498ab79b29ff00b9f",
    "type":"Axure:Page",
    "name":"人机工程学",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bd207040ffe541388acf9cb72dd9dd5a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":1280,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4979f426649497ba2f1516bdc5f95c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":1280,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u7.png"}},
{
          "id":"7b1daeaa444a461687a4b2df9eced9fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":413,
              "y":26},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3b27eb8ebc34c9facadfa09a75f2ac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":413,
                  "y":26},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 INDEX",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"c0bcf390e5354023bbeae3f51791ce25",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":672,
              "y":26},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38056ab9951c4edc8bc98b585c683e8a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":672,
                  "y":26},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 DESIGN",
                      "target":{
                        "targetType":"page",
                        "url":"design.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9a1cafef96a847dbb8f0c887566020ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":899,
              "y":26},
            "size":{
              "width":99,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc878c1c792d44f083e0198318154617",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":899,
                  "y":26},
                "size":{
                  "width":99,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FRONT-END",
                      "target":{
                        "targetType":"page",
                        "url":"front-end.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"40729092dc8f45dea6dcb44406c99f00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1173,
              "y":26},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc0b8333c1b74455bcd205ac6d6e9e62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1173,
                  "y":26},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GAME",
                      "target":{
                        "targetType":"page",
                        "url":"game.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"51a13a62ebf0414c9af99dadbdbf78f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1390,
              "y":26},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18090efa6afb43d7a1b42df683d3814c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1390,
                  "y":26},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GITHUB",
                      "target":{
                        "targetType":"page",
                        "url":"github.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"768b0171b9b04561925e9963429b95a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":310,
              "y":67},
            "size":{
              "width":1280,
              "height":1360},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a48b61a6182a429dbb1f4c2f94fee296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":310,
                  "y":67},
                "size":{
                  "width":1280,
                  "height":1360},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/材料与工艺/u12.png"}},
{
          "id":"28127208ba2e4e71820edbec6cf650d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":870,
              "y":90},
            "size":{
              "width":161,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"911ff26938ca4688a69a1a19c5c450b1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":870,
                  "y":90},
                "size":{
                  "width":161,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"786f6cec20c14d4d9efdbc08ce0d361d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":430,
              "y":190},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"979adae7ddcd4c5498374927884d209b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":430,
                  "y":190},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/design/u35.jpg"}},
{
          "id":"762ab891793240e497b91ce13e6fae40",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1043,
              "y":190},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0a22370f13d3424e86903c72b1d901ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1043,
                  "y":190},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/人机工程学/u18.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "bd207040ffe541388acf9cb72dd9dd5a":{
      "scriptId":"u0"},
    "b4979f426649497ba2f1516bdc5f95c4":{
      "scriptId":"u1"},
    "7b1daeaa444a461687a4b2df9eced9fa":{
      "scriptId":"u2"},
    "b3b27eb8ebc34c9facadfa09a75f2ac8":{
      "scriptId":"u3"},
    "c0bcf390e5354023bbeae3f51791ce25":{
      "scriptId":"u4"},
    "38056ab9951c4edc8bc98b585c683e8a":{
      "scriptId":"u5"},
    "9a1cafef96a847dbb8f0c887566020ef":{
      "scriptId":"u6"},
    "fc878c1c792d44f083e0198318154617":{
      "scriptId":"u7"},
    "40729092dc8f45dea6dcb44406c99f00":{
      "scriptId":"u8"},
    "cc0b8333c1b74455bcd205ac6d6e9e62":{
      "scriptId":"u9"},
    "51a13a62ebf0414c9af99dadbdbf78f7":{
      "scriptId":"u10"},
    "18090efa6afb43d7a1b42df683d3814c":{
      "scriptId":"u11"},
    "768b0171b9b04561925e9963429b95a8":{
      "scriptId":"u12"},
    "a48b61a6182a429dbb1f4c2f94fee296":{
      "scriptId":"u13"},
    "28127208ba2e4e71820edbec6cf650d6":{
      "scriptId":"u14"},
    "911ff26938ca4688a69a1a19c5c450b1":{
      "scriptId":"u15"},
    "786f6cec20c14d4d9efdbc08ce0d361d":{
      "scriptId":"u16"},
    "979adae7ddcd4c5498374927884d209b":{
      "scriptId":"u17"},
    "762ab891793240e497b91ce13e6fae40":{
      "scriptId":"u18"},
    "0a22370f13d3424e86903c72b1d901ef":{
      "scriptId":"u19"}}});