$axure.loadCurrentPage({
  "url":"设计初步.html",
  "generationDate":new Date(1476259092933.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"70f87196527d402eadf1664388a24576",
    "type":"Axure:Page",
    "name":"设计初步",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cd2fc34b859b4fe1afbe91c8124400f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"700",
            "fill":{
              "fillType":"solid",
              "color":0xFF000000},
            "location":{
              "x":310,
              "y":0},
            "size":{
              "width":1280,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4df215a6b9cb4e009991a385b6a94dc7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"700",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "location":{
                  "x":310,
                  "y":0},
                "size":{
                  "width":1280,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u7.png"}},
{
          "id":"02d7debcdd5e4640b86eb428f28841ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":413,
              "y":26},
            "size":{
              "width":52,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90dd432704ff40559d23272eb32fe5d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":413,
                  "y":26},
                "size":{
                  "width":52,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 INDEX",
                      "target":{
                        "targetType":"page",
                        "url":"index.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"736dfcf72496497abd54647151237db1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":672,
              "y":26},
            "size":{
              "width":60,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3db67c6faf404eb3b7cb39f8d6c439eb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":672,
                  "y":26},
                "size":{
                  "width":60,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 DESIGN",
                      "target":{
                        "targetType":"page",
                        "url":"design.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"69fa24a052764e488a77a21810ed0529",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":899,
              "y":26},
            "size":{
              "width":99,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7bbcd20f51d4071bbb1bc419d62f198",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":899,
                  "y":26},
                "size":{
                  "width":99,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 FRONT-END",
                      "target":{
                        "targetType":"page",
                        "url":"front-end.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"176c4ee3dd4b4eceb6fec0b0b6def1da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1173,
              "y":26},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7259b012f574273bb26a00e8fdc1c6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1173,
                  "y":26},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GAME",
                      "target":{
                        "targetType":"page",
                        "url":"game.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"cb64cd8e2c9e4542a6caa4683eaf327f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9CABB,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1}}},
            "location":{
              "x":1390,
              "y":26},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f861164bc54adc8d057508cda556ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9CABB,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1}}},
                "location":{
                  "x":1390,
                  "y":26},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"closeCurrent",
                      "description":"关闭当前窗口"},
{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 GITHUB",
                      "target":{
                        "targetType":"page",
                        "url":"github.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"ec4a040b8ec544cc8a7be6b49b6ef793",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fill":{
              "fillType":"solid",
              "color":0xFF363636},
            "location":{
              "x":310,
              "y":67},
            "size":{
              "width":1280,
              "height":1360},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdf55939804a454686507e68ac6404a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fill":{
                  "fillType":"solid",
                  "color":0xFF363636},
                "location":{
                  "x":310,
                  "y":67},
                "size":{
                  "width":1280,
                  "height":1360},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/材料与工艺/u12.png"}},
{
          "id":"93d85aa79ab24d0d82865362c854624c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":885.5,
              "y":90},
            "size":{
              "width":129,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab6cc05deea14cb193cdaa7da8e30de1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":885.5,
                  "y":90},
                "size":{
                  "width":129,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fbc7e49da2cb43e99a834b1bc15c1382",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1040,
              "y":180},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0918b388a3d44c9af1dd397662847b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1040,
                  "y":180},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计初步/u16.jpg"}},
{
          "id":"485bb584409e487882dfa81468cf575b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":1040,
              "y":540},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"335821c2984149e48261d340e8775e36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":1040,
                  "y":540},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计初步/u18.jpg"}},
{
          "id":"aee044aa41f2472aa94ab983c062e1ae",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":433,
              "y":540},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd03f48e8ab448cb8d27fb33bf44f6e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":433,
                  "y":540},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/设计初步/u20.jpg"}},
{
          "id":"ebe904823cfa4097874fb0315c8b255d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":433,
              "y":180},
            "size":{
              "width":427,
              "height":290}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76462880ae21424593d299cbe5f5816b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":433,
                  "y":180},
                "size":{
                  "width":427,
                  "height":290}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/design/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "cd2fc34b859b4fe1afbe91c8124400f1":{
      "scriptId":"u0"},
    "4df215a6b9cb4e009991a385b6a94dc7":{
      "scriptId":"u1"},
    "02d7debcdd5e4640b86eb428f28841ff":{
      "scriptId":"u2"},
    "90dd432704ff40559d23272eb32fe5d7":{
      "scriptId":"u3"},
    "736dfcf72496497abd54647151237db1":{
      "scriptId":"u4"},
    "3db67c6faf404eb3b7cb39f8d6c439eb":{
      "scriptId":"u5"},
    "69fa24a052764e488a77a21810ed0529":{
      "scriptId":"u6"},
    "a7bbcd20f51d4071bbb1bc419d62f198":{
      "scriptId":"u7"},
    "176c4ee3dd4b4eceb6fec0b0b6def1da":{
      "scriptId":"u8"},
    "e7259b012f574273bb26a00e8fdc1c6c":{
      "scriptId":"u9"},
    "cb64cd8e2c9e4542a6caa4683eaf327f":{
      "scriptId":"u10"},
    "a4f861164bc54adc8d057508cda556ae":{
      "scriptId":"u11"},
    "ec4a040b8ec544cc8a7be6b49b6ef793":{
      "scriptId":"u12"},
    "fdf55939804a454686507e68ac6404a0":{
      "scriptId":"u13"},
    "93d85aa79ab24d0d82865362c854624c":{
      "scriptId":"u14"},
    "ab6cc05deea14cb193cdaa7da8e30de1":{
      "scriptId":"u15"},
    "fbc7e49da2cb43e99a834b1bc15c1382":{
      "scriptId":"u16"},
    "f0918b388a3d44c9af1dd397662847b0":{
      "scriptId":"u17"},
    "485bb584409e487882dfa81468cf575b":{
      "scriptId":"u18"},
    "335821c2984149e48261d340e8775e36":{
      "scriptId":"u19"},
    "aee044aa41f2472aa94ab983c062e1ae":{
      "scriptId":"u20"},
    "cd03f48e8ab448cb8d27fb33bf44f6e5":{
      "scriptId":"u21"},
    "ebe904823cfa4097874fb0315c8b255d":{
      "scriptId":"u22"},
    "76462880ae21424593d299cbe5f5816b":{
      "scriptId":"u23"}}});